
# Coupling host parameters
total_time: 5.0
n_steps: 1000

# What about the comm_nspan and comm_nchord, eta_cp?

host: "127.0.0.1"
port: 9000

comm_nspan: 80
comm_nchord: 1


# Should be transferred to coupling.yaml 
work_conservative_mode: true
work_conservation_mode: true

# striding parameters - coupling.yaml
span_sampling_mode: "node-stride" # need to explore custom stride during sweeps
custom_span_stride: null

# Work conservation operator parameters - same in coupling.yaml
force_transfer_mode: "rbf" # options: "rbf" or "crm"
rbf_radius: 0.08
rbf_neighbors: 24
max_abs_force_component: 5.0e3 # clipping? @neeraj pls check this by making it high
enforce_chord_projection: false
enforce_span_projection: false

force_relax: 1.0
geom_relax: 1.0

debug_io:
payload_indexing:

send_cp: true 
send_le: true
send_te: true
