run_name: static_airfoil_spanwise
particles_per_step: 1
save_every: 1
aoa_deg: 8.0
vinf: 8.0
rho: 1.0
nu: 1.0e-06
twist_root: 0.0
twist_tip: 0.0
dihedral: 0.0
n_span: 80
n_chord: 1
eta_cp: 0.75
eta_bv: 0.25
x: 1.0
y: 1.0
z: 1.0
lambda_vpm: 2.0
remove_every: 100
sphere_factor: 200.0
min_factor: 0.001
max_factor: 50.0
wake_coupled: true
start_with_wake: true
unsteady: true
unsteady_criterion: 0.0
omit_rows: []
relaxation: 0.35
sigma_solver: -1
sigma_surface: 0.05
p: 4
ncrit: 50
theta: 0.4
shrink_recenter: true
relative_tolerance: 1e-3
absolute_tolerance: 1e-3
autotune_p: true
autotune_ncrit: true
autotune_regularization: false
default_rho_over_sigma: 1.0
minimum_ncrit: 3
viscous_scheme: CoreSpreading
save_directory: results/dt_0.001_fig_reversetransfer/fluid/
create_directory: true
create_savepath: true
prompt: false
io: false
print_solver_info: true
save_geometry_csv: true
save_force_history: true
save_diagnostics: true
save_horseshoes: true
regularize_vlm: true
use_ftot_force: true
nsteps_save: 2
