
# Coupling host parameters
total_time: 5.0
n_steps: 1000



host: "127.0.0.1"
port: 9000


# Should be transferred to coupling.yaml 
work_conservative_mode: True
#work_conservation_mode: true

# striding parameters - coupling.yaml
span_sampling_mode: "node-stride" # need to explore custom stride during sweeps
custom_span_stride: None

# Work conservation operator parameters - same in coupling.yaml
rbf_radius: 0.08
rbf_neighbors: 24
max_abs_force_component: 5.0e3 # clipping? @neeraj pls check this by making it high
enforce_chord_projection: False
enforce_span_projection: False

force_relax: 1.0
geom_relax: 1.0
